temp

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -57,3 +57,15 @@ before_script:
   - chmod +x gradlew
   - ./gradlew --version
   - ./gradlew clean
+
+
+script:
+  - |
+    ./gradlew installDebug installDebugAndroidTest
+    retval=$?
+    if [ $retval -ne 0 ]; then
+      echo "error on install, exit code: "$retval
+      exit $retval
+    fi
+
+  - ./gradlew build connectedCheck
